import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-neutral-950 antialiased`}
      >
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
